### ISSUE TITLE
SPI interface pinout

### ISSUE THREAD

**Issue by kaklik** [mlab-modules/FRAM01A#1]
Vidím že konektor pro připojení má nyní takovýhle pinout: 

![image](https://github.com/mlab-modules/FRAM01/assets/1194177/42d2609d-1c5d-4359-9c69-24260646ab20)

Kam se to bude připojovat? Přijde mi, že to neodpovídá žádnému současnému rozložení konektorů.

**Comment by Sommema4** [comment]
Jo, já jsem tohle rozložení našel jako rozložení pro SPI. Nevím přesně, kde jsem to našel. Už je to nějaká doba, kdy jsem to dělal. Stejný rozložení jsem použil například u ALTIMET02.
Je tam akorát přidaný ještě jeden "řádek", aby se dal využít Write Protection pin. Ten pin lze připojit na Vcc a nepoužívat ho. Tím se může ten konektor zredukovat o 2 piny. Snažil jsem se zachovat co nejvíc funkcionalit toho IC, proto je tam takový rozložení.

**Comment by kaklik** [comment]
Ok, vypadá to, že je to docela [běžný rozložení](https://duckduckgo.com/?q=spi+avr+connector+pinout&t=ffab&iar=images&iax=images&ia=images) jen z toho popisu na PCB mi to nebylo jasný.
